name: student_presence
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Ajout des dépendances responsive_builder et responsive_framework
  responsive_builder: ^0.4.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_ui_auth: ^1.14.0
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
